In [1]:
import geopandas as gpd
import pandas as pd

In [4]:
seoul = gpd.read_file('Data/processed_soul.shp', encoding='utf-8')
seoul

,EMD_CD,EMD_NM,SGG_OID,COL_ADM_SE,GID,SI_NAME,geometry
0,11290129,보문동7가,7,11290,5222,성북구,"POLYGON ((957864.444 1953662.735, 957878.870 1..."
1,11290103,돈암동,8,11290,5223,성북구,"POLYGON ((956352.458 1955412.808, 956340.774 1..."
2,11290139,석관동,9,11290,5224,성북구,"POLYGON ((961229.416 1956099.120, 961229.075 1..."
3,11290114,삼선동4가,22,11290,5225,성북구,"POLYGON ((957329.114 1954659.435, 957325.653 1..."
4,11290117,동선동2가,29,11290,5232,성북구,"POLYGON ((957516.003 1954475.929, 957510.279 1..."
...,...,...,...,...,...,...,...
462,11230102,용두동,705,11230,2658,동대문구,"POLYGON ((958007.385 1953418.674, 958018.560 1..."
463,11230107,청량리동,376,11230,2659,동대문구,"POLYGON ((959280.728 1954765.510, 959294.400 1..."
464,11410112,대현동,1714,11410,2660,서대문구,"POLYGON ((950576.143 1951255.737, 950585.933 1..."
465,11110157,인의동,348,11110,2661,종로구,"POLYGON ((955531.438 1952843.236, 955532.337 1..."
466,11110150,훈정동,332,11110,2662,종로구,"POLYGON ((955466.246 1953099.971, 955471.458 1..."

In [5]:
seoul.drop('SGG_OID', axis=1, inplace=True)
seoul.drop('COL_ADM_SE', axis=1, inplace=True)
seoul.drop('GID', axis=1, inplace=True)

In [8]:
#bab_cnt = pd.read_csv('Data/Tableau_Data/BaB_cnt_cal_pop.csv')
#bab_cnt

In [9]:
seoul.to_file("Data/Tableau_Data/processed_soul.shp", encoding='utf-8')