In [21]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests
import urllib.request as ul
from tqdm import tqdm
import json
import sys
import io
import re

In [142]:
bus = pd.read_excel('최종2_좌표, 주소 데이터.xlsx', sheet_name="편의_편의점")
bus.head()

,지점명,주소,시군구,읍면동,xpos,ypos
0,CU 성대원룸촌점,"서울특별시 종로구 성균관로 36, (명륜1가)",종로구,혜화동,126.996994,37.585879
1,미니스톱 종로육의전점,서울특별시 종로구 수표로 105,종로구,종로1·2·3·4가동,126.989206,37.570621
2,CU 종로국악당점,서울특별시 종로구 율곡로 10길 16,종로구,종로1·2·3·4가동,126.990889,37.576780
3,CU 종로운현궁점,서울특별시 종로구 율곡로 52,종로구,종로1·2·3·4가동,126.985371,37.576237
4,세븐일레븐 종로서촌점,서울특별시 종로구 자하문로 18-1층,종로구,사직동,126.972330,37.577819

In [143]:
bus = pd.read_excel('최종2_좌표, 주소 데이터.xlsx', sheet_name="편의_편의점")
#data.drop('Unnamed: 0', axis=1, inplace=True)
#bus.drop('시도명', axis=1, inplace=True)
#bus.drop('Unnamed: 9', axis=1, inplace=True)
#bus.drop('Unnamed: 8', axis=1, inplace=True)
#bus.drop('Unnamed: 10', axis=1, inplace=True)
#bus.drop('Unnamed: 11', axis=1, inplace=True)
#bus.drop('Unnamed: 12', axis=1, inplace=True)
bus.drop('시군구', axis=1, inplace=True)
bus.drop('읍면동', axis=1, inplace=True)
bus.head()

           지점명                         주소        xpos       ypos
0    CU 성대원룸촌점  서울특별시 종로구 성균관로 36, (명륜1가)  126.996994  37.585879
1  미니스톱 종로육의전점          서울특별시 종로구 수표로 105  126.989206  37.570621
2    CU 종로국악당점       서울특별시 종로구 율곡로 10길 16  126.990889  37.576780
3    CU 종로운현궁점           서울특별시 종로구 율곡로 52  126.985371  37.576237
4  세븐일레븐 종로서촌점       서울특별시 종로구 자하문로 18-1층  126.972330  37.577819

In [144]:
bus.shape

(8135, 4)

In [145]:
lat = bus['xpos'][0]
log = bus['ypos'][0]

In [146]:
url = "https://dapi.kakao.com/v2/local/geo/coord2regioncode.json?x={}&y={}".format(lat, log)
headers = {"Authorization": "KakaoAK 1d53225a36103804a9bb5d0585243989"}
api_test = requests.get(url,headers=headers)
url_text = json.loads(api_test.text)

In [147]:
url_text

{'meta': {'total_count': 2},
 'documents': [{'region_type': 'B',
   'code': '1111017000',
   'address_name': '서울특별시 종로구 명륜1가',
   'region_1depth_name': '서울특별시',
   'region_2depth_name': '종로구',
   'region_3depth_name': '명륜1가',
   'region_4depth_name': '',
   'x': 126.99746830452213,
   'y': 37.58910769214281},
  {'region_type': 'H',
   'code': '1111065000',
   'address_name': '서울특별시 종로구 혜화동',
   'region_1depth_name': '서울특별시',
   'region_2depth_name': '종로구',
   'region_3depth_name': '혜화동',
   'region_4depth_name': '',
   'x': 127.0006204504988,
   'y': 37.586855235994356}]}

In [148]:
region_type1_list = []
code_1_list = []
region_f_1_list = []
region_s_1_list = []
region_t_1_list = []

region_type2_list = []
code_2_list = []
region_f_2_list = []
region_s_2_list = []
region_t_2_list = []


for i in tqdm(range(len(bus))):
    lat = bus['xpos'][i]
    log = bus['ypos'][i]
        
    url = "https://dapi.kakao.com/v2/local/geo/coord2regioncode.json?x={}&y={}".format(lat, log)
    headers = {"Authorization": "KakaoAK 1d53225a36103804a9bb5d0585243989"}
    api_test = requests.get(url,headers=headers)
    url_text = json.loads(api_test.text)
    
    try:
        region_type1 = url_text['documents'][0]['region_type']
        code_1 = url_text['documents'][0]['code']
        region_f_1 = url_text['documents'][0]['region_1depth_name']
        region_s_1 = url_text['documents'][0]['region_2depth_name']
        region_t_1 = url_text['documents'][0]['region_3depth_name']
    except:
        region_type1 = ''
        code_1 = ''
        region_f_1 = ''
        region_s_1 = ''
        region_t_1 = ''
        print('except! on 1')
    try:
        region_type2 = url_text['documents'][1]['region_type']
        code_2 = url_text['documents'][1]['code']
        region_f_2 = url_text['documents'][1]['region_1depth_name']
        region_s_2 = url_text['documents'][1]['region_2depth_name']
        region_t_2 = url_text['documents'][1]['region_3depth_name']
    except:
        region_type2 = ''
        code_2 = ''
        region_f_2 = ''
        region_s_2 = ''
        region_t_2 = ''
        print('except! on 2')
        
    region_type1_list.append(region_type1)
    code_1_list.append(code_1)
    region_f_1_list.append(region_f_1)
    region_s_1_list.append(region_s_1)
    region_t_1_list.append(region_t_1)

    region_type2_list.append(region_type2)
    code_2_list.append(code_2)
    region_f_2_list.append(region_f_2)
    region_s_2_list.append(region_s_2)
    region_t_2_list.append(region_t_2)

100%|███████████████████████████████████████| 8135/8135 [16:11<00:00,  8.37it/s]

In [149]:
B_H = pd.DataFrame(np.column_stack([region_type1_list, code_1_list, region_f_1_list, region_s_1_list, region_t_1_list,
                                               region_type2_list, code_2_list, region_f_2_list, region_s_2_list, region_t_2_list]), 
                               columns=['법정동', '법정동코드', 'B_시도명', 'B_시군구', 'B_동',
                                       '행정동', '행정동코드', 'H_시도명', 'H_시군구', 'H_동'])
B_H

,법정동,법정동코드,B_시도명,B_시군구,B_동,행정동,행정동코드,H_시도명,H_시군구,H_동
0,B,1111017000,서울특별시,종로구,명륜1가,H,1111065000,서울특별시,종로구,혜화동
1,B,1111013800,서울특별시,종로구,종로2가,H,1111061500,서울특별시,종로구,종로1.2.3.4가동
2,B,1111013000,서울특별시,종로구,와룡동,H,1111061500,서울특별시,종로구,종로1.2.3.4가동
3,B,1111013400,서울특별시,종로구,경운동,H,1111061500,서울특별시,종로구,종로1.2.3.4가동
4,B,1111010600,서울특별시,종로구,통의동,H,1111053000,서울특별시,종로구,사직동
...,...,...,...,...,...,...,...,...,...,...
8130,B,1174010800,서울특별시,강동구,성내동,H,1174064000,서울특별시,강동구,성내1동
8131,B,1174010800,서울특별시,강동구,성내동,H,1174064000,서울특별시,강동구,성내1동
8132,B,1174010800,서울특별시,강동구,성내동,H,1174064000,서울특별시,강동구,성내1동
8133,B,1174010500,서울특별시,강동구,길동,H,1174068500,서울특별시,강동구,길동
8134,B,1174010800,서울특별시,강동구,성내동,H,1174064000,서울특별시,강동구,성내1동

In [150]:
fin = pd.concat([bus, B_H], axis=1)
fin

,지점명,주소,xpos,ypos,법정동,법정동코드,B_시도명,B_시군구,B_동,행정동,행정동코드,H_시도명,H_시군구,H_동
0,CU 성대원룸촌점,"서울특별시 종로구 성균관로 36, (명륜1가)",126.996994,37.585879,B,1111017000,서울특별시,종로구,명륜1가,H,1111065000,서울특별시,종로구,혜화동
1,미니스톱 종로육의전점,서울특별시 종로구 수표로 105,126.989206,37.570621,B,1111013800,서울특별시,종로구,종로2가,H,1111061500,서울특별시,종로구,종로1.2.3.4가동
2,CU 종로국악당점,서울특별시 종로구 율곡로 10길 16,126.990889,37.576780,B,1111013000,서울특별시,종로구,와룡동,H,1111061500,서울특별시,종로구,종로1.2.3.4가동
3,CU 종로운현궁점,서울특별시 종로구 율곡로 52,126.985371,37.576237,B,1111013400,서울특별시,종로구,경운동,H,1111061500,서울특별시,종로구,종로1.2.3.4가동
4,세븐일레븐 종로서촌점,서울특별시 종로구 자하문로 18-1층,126.972330,37.577819,B,1111010600,서울특별시,종로구,통의동,H,1111053000,서울특별시,종로구,사직동
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8130,GS25 GS25강동성일점,"서울 강동구 성내로 13길14, 1층 102호 (성내동 543)",127.127541,37.528661,B,1174010800,서울특별시,강동구,성내동,H,1174064000,서울특별시,강동구,성내1동
8131,미니스톱 강동구청점,서울 강동구 성내로 5길 19,127.123489,37.530758,B,1174010800,서울특별시,강동구,성내동,H,1174064000,서울특별시,강동구,성내1동
8132,GS25 GS25강동베르네점,"서울 강동구 성내로 6길20, 108호 (성내1동 556-2, 청일 베르네)",127.122344,37.529019,B,1174010800,서울특별시,강동구,성내동,H,1174064000,서울특별시,강동구,성내1동
8133,GS25 GS25강동성심점,"서울 강동구 성안로 156, 1층 3호 (길동 416-6, 우주빌딩)",127.135412,37.536874,B,1174010500,서울특별시,강동구,길동,H,1174068500,서울특별시,강동구,길동
8134,GS25 GS25성내동원점,서울 강동구 성안로 3길104 (성내동 560-4),127.124439,37.527863,B,1174010800,서울특별시,강동구,성내동,H,1174064000,서울특별시,강동구,성내1동

In [152]:
fin.to_csv('Fin_data/편의_편의점.csv', encoding='utf-8-sig')

- 의료_병원 데이터에서 2개 빠진 부분 구글링하여 채움.